package com.limin.blog.mapper;

import com.limin.blog.model.ArticleCategory;
import com.limin.blog.model.ArticleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    long countByExample(ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int deleteByExample(ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int insert(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int insertSelective(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    List<ArticleCategory> selectByExample(ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleCategory record, @Param("example") ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int updateByExample(@Param("record") ArticleCategory record, @Param("example") ArticleCategoryExample example);
}