package com.limin.blog.mapper;

import com.limin.blog.model.SysCategory;
import com.limin.blog.model.SysCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    long countByExample(SysCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int deleteByExample(SysCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int insert(SysCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int insertSelective(SysCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    List<SysCategory> selectByExample(SysCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    SysCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysCategory record, @Param("example") SysCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int updateByExample(@Param("record") SysCategory record, @Param("example") SysCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int updateByPrimaryKeySelective(SysCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    int updateByPrimaryKey(SysCategory record);
}