package com.limin.blog.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article_category
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 10 20:03:55 CST 2018
 */
public class ArticleCategory {
    /**
     * Database Column Remarks:
     *   文章id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.article_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer articleId;

    /**
     * Database Column Remarks:
     *   个人分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.article_id
     *
     * @return the value of article_category.article_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.article_id
     *
     * @param articleId the value for article_category.article_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_id
     *
     * @return the value of article_category.category_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_id
     *
     * @param categoryId the value for article_category.category_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}