package com.limin.blog.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 10 20:03:55 CST 2018
 */
public class Article {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.user_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   系统分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sys_cate_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer sysCateId;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String title;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.release_date
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Date releaseDate;

    /**
     * Database Column Remarks:
     *   阅读数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.read_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer readNum;

    /**
     * Database Column Remarks:
     *   评论数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer commentNum;

    /**
     * Database Column Remarks:
     *   是否原创
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   是否公开
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.is_private
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Boolean isPrivate;

    /**
     * Database Column Remarks:
     *   能否评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.is_comment
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Boolean isComment;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.user_id
     *
     * @return the value of article.user_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.user_id
     *
     * @param userId the value for article.user_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sys_cate_id
     *
     * @return the value of article.sys_cate_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getSysCateId() {
        return sysCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sys_cate_id
     *
     * @param sysCateId the value for article.sys_cate_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setSysCateId(Integer sysCateId) {
        this.sysCateId = sysCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.release_date
     *
     * @return the value of article.release_date
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.release_date
     *
     * @param releaseDate the value for article.release_date
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.read_num
     *
     * @return the value of article.read_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.read_num
     *
     * @param readNum the value for article.read_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment_num
     *
     * @return the value of article.comment_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment_num
     *
     * @param commentNum the value for article.comment_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type
     *
     * @return the value of article.type
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type
     *
     * @param type the value for article.type
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.is_private
     *
     * @return the value of article.is_private
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Boolean getIsPrivate() {
        return isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.is_private
     *
     * @param isPrivate the value for article.is_private
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.is_comment
     *
     * @return the value of article.is_comment
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Boolean getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.is_comment
     *
     * @param isComment the value for article.is_comment
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setIsComment(Boolean isComment) {
        this.isComment = isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}