package com.limin.blog.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table category
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 10 20:03:55 CST 2018
 */
public class Category {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.user_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String name;

    /**
     * Database Column Remarks:
     *   文章数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.article_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer articleNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.user_id
     *
     * @return the value of category.user_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.user_id
     *
     * @param userId the value for category.user_id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.article_num
     *
     * @return the value of category.article_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getArticleNum() {
        return articleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.article_num
     *
     * @param articleNum the value for category.article_num
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setArticleNum(Integer articleNum) {
        this.articleNum = articleNum;
    }
}