package com.limin.blog.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_category
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 10 20:03:55 CST 2018
 */
public class SysCategory {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   系统分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.status
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.id
     *
     * @return the value of sys_category.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.id
     *
     * @param id the value for sys_category.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.name
     *
     * @return the value of sys_category.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.name
     *
     * @param name the value for sys_category.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.status
     *
     * @return the value of sys_category.status
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.status
     *
     * @param status the value for sys_category.status
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}