package com.limin.blog.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 10 20:03:55 CST 2018
 */
public class User {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String name;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String password;

    /**
     * Database Column Remarks:
     *   盐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String salt;

    /**
     * Database Column Remarks:
     *   头像url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head_url
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String headUrl;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String email;

    /**
     * Database Column Remarks:
     *   座右铭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.motto
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private String motto;

    /**
     * Database Column Remarks:
     *   入驻时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birth
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Date birth;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.salt
     *
     * @return the value of user.salt
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.salt
     *
     * @param salt the value for user.salt
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_url
     *
     * @return the value of user.head_url
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_url
     *
     * @param headUrl the value for user.head_url
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.motto
     *
     * @return the value of user.motto
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public String getMotto() {
        return motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.motto
     *
     * @param motto the value for user.motto
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setMotto(String motto) {
        this.motto = motto == null ? null : motto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birth
     *
     * @return the value of user.birth
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birth
     *
     * @param birth the value for user.birth
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     *
     * @mbg.generated Tue Apr 10 20:03:55 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}